// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using choir_music_system.Data;

#nullable disable

namespace choir_music_system.Migrations
{
    [DbContext(typeof(ChoirDbContext))]
    [Migration("20260903064411_AddFinalMassPresentation")]
    partial class AddFinalMassPresentation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("choir_music_system.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitedBy")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("choir_music_system.Models.Mass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalPresentationFileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalPresentationPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalPresentationUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MassDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MassIntroduction")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentationBackgroundPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Masses");
                });

            modelBuilder.Entity("choir_music_system.Models.MassPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MassPart")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PresentationItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MassId");

                    b.HasIndex("PresentationItemId");

                    b.HasIndex("SongId");

                    b.ToTable("MassPlanItems");
                });

            modelBuilder.Entity("choir_music_system.Models.MassSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MassPart")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MusicSheetId");

                    b.HasKey("Id");

                    b.HasIndex("MassId");

                    b.HasIndex("SongId");

                    b.ToTable("MassMusicSheets", (string)null);
                });

            modelBuilder.Entity("choir_music_system.Models.MassTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MassTemplates");
                });

            modelBuilder.Entity("choir_music_system.Models.MassTemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MassPart")
                        .HasColumnType("TEXT");

                    b.Property<int>("MassTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PresentationItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MassTemplateId");

                    b.HasIndex("PresentationItemId");

                    b.HasIndex("SongId");

                    b.ToTable("MassTemplateItems");
                });

            modelBuilder.Entity("choir_music_system.Models.PresentationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerPointLayout")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentationText")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PresentationItems");
                });

            modelBuilder.Entity("choir_music_system.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arrangement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Composer")
                        .HasColumnType("TEXT");

                    b.Property<string>("CopyrightText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomPresentationFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomPresentationPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CustomPresentationUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OneLicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentationLyrics")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedMassPart")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MusicSheets", (string)null);
                });

            modelBuilder.Entity("choir_music_system.Models.MassPlanItem", b =>
                {
                    b.HasOne("choir_music_system.Models.Mass", "Mass")
                        .WithMany("PlanItems")
                        .HasForeignKey("MassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("choir_music_system.Models.PresentationItem", "PresentationItem")
                        .WithMany()
                        .HasForeignKey("PresentationItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("choir_music_system.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mass");

                    b.Navigation("PresentationItem");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("choir_music_system.Models.MassSong", b =>
                {
                    b.HasOne("choir_music_system.Models.Mass", "Mass")
                        .WithMany("Songs")
                        .HasForeignKey("MassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("choir_music_system.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mass");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("choir_music_system.Models.MassTemplateItem", b =>
                {
                    b.HasOne("choir_music_system.Models.MassTemplate", "MassTemplate")
                        .WithMany("Items")
                        .HasForeignKey("MassTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("choir_music_system.Models.PresentationItem", "PresentationItem")
                        .WithMany()
                        .HasForeignKey("PresentationItemId");

                    b.HasOne("choir_music_system.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId");

                    b.Navigation("MassTemplate");

                    b.Navigation("PresentationItem");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("choir_music_system.Models.Mass", b =>
                {
                    b.Navigation("PlanItems");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("choir_music_system.Models.MassTemplate", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
